name: Triumph Motorcycles CI CD

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']

    # Basic setup for unit testing
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Prepare node
        run: npm ci
      - name: Running prettier
        run: npm run prettier
      - name: Running unit tests
        run: npm run test

  # Setup for e2e testing with Cypress

  # on Chrome - Components
  # chrome-component:
  #   runs-on: ubuntu-latest
  #   name: Components on Chrome
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install dependencies
  #       uses: cypress-io/github-action@v6
  #       with:
  #         runTests: false
  #         working-directory: ./src/infrastructure/frontend
  #     - name: Run npm ci
  #       run: npm ci
  #       working-directory: ./src/infrastructure/frontend
  #     - name: Run components tests
  #       uses: cypress-io/github-action@v6
  #       with:
  #         install: false
  #         working-directory: ./src/infrastructure/frontend
  #         component: true
  #         browser: chrome

  # on Chrome - E2E
  chrome-e2e:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          working-directory: ./src/infrastructure/frontend
      - name: Run npm ci
        run: npm ci
        working-directory: ./src/infrastructure/frontend
      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: ./src/infrastructure/frontend
          browser: chrome
          build: npm run build
          start: npm run dev

  # on Firefox - Components
  # firefox-component:
  #   runs-on: ubuntu-latest
  #   name: Components on FireFox
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install dependencies
  #       uses: cypress-io/github-action@v6
  #       with:
  #         runTests: false
  #         working-directory: ./src/infrastructure/frontend
  #     - name: Run npm ci
  #       run: npm ci
  #       working-directory: ./src/infrastructure/frontend
  #     - name: Run components tests
  #       uses: cypress-io/github-action@v6
  #       with:
  #         install: false
  #         working-directory: ./src/infrastructure/frontend
  #         component: true
  #         browser: firefox

  # on FireFox - E2E
  firefox-e2e:
    runs-on: ubuntu-latest
    name: E2E on FireFox
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          working-directory: ./src/infrastructure/frontend
      - name: Run npm ci
        run: npm ci
        working-directory: ./src/infrastructure/frontend
      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: ./src/infrastructure/frontend
          browser: firefox
          build: npm run build
          start: npm run dev
# TODO : deploy
