name: Triumph Motorcycles CI CD

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']

    # Basic setup for unit testing
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Prepare node
        run: npm ci
      - name: Building the App
        run: npm run build --if-present
      - name: Running prettier
        run: npm run prettier
      - name: Running lint and unit tests
        run: npm run test:unit

  # Setup for e2e testing with Cypress

  # on Chrome - Components
  chrome-component:
    runs-on: ubuntu-latest
    name: Components on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          component: true
          browser: chrome

  # on Chrome - E2E
  chrome-e2e:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: npm run build
          start: npm run dev

  # on Firefox - Components
  firefox-component:
    runs-on: ubuntu-latest
    name: Components on Firefox
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          component: true
          browser: firefox

  # on Chrome - E2E
  firefox-e2e:
    runs-on: ubuntu-latest
    name: E2E on Firefox
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: firefox
          build: npm run build
          start: npm run dev
# TODO : deploy
