name: Triumph Motorcycles CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']

    # Basic setup for unit testing
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Prepare node
        run: npm ci
      - name: Building the App
        run: npm run build --if-present
      - name: Running lint and unit tests
        run: npm run test:unit

  # Setup for e2e testing with Cypress

  # on Chrome
  chrome:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          component: true
          build: npm run build
          start: npm start
          browser: chrome

  # on Firefox
  firefox:
    runs-on: ubuntu-latest
    name: E2E on Firefox
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          component: true
          build: npm run build
          start: npm start
          browser: firefox
# TODO : deploy
